### ISSUE TITLE
[Regression]Default values are no more added on attribute completion

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#150]
when calling completion for instance on "timer:timerName?" and choose "period"
it should end up with "timer:timerName?period=1000" but it currently completes with ""timer:timerName?period" only

**Comment by apupier** [comment]
introduced with https://github.com/camel-tooling/camel-language-server/issues/55

**Comment by apupier** [comment]
another related issue detected:
when the uri is empty, there is no completion

**Comment by tsedmik** [comment]
verified in Eclipse (standalone) - Tooling for Apache Camel based on Apache Camel implementation of Language Server Protocol 1.0.0.201809120921
