### ISSUE TITLE
Upgrade from SpringBoot 1.4.0 to 2+

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#152]

**Comment by smieras** [comment]
@apupier Assuming you mean upgrading the spring-boot-maven plugin, I would like to help out :)

**Comment by apupier** [comment]
@smieras yes, i'm mean that
the idea is to upgrade it and then try the generated artefacts with [vscode ](https://github.com/camel-tooling/camel-lsp-client-vscode) and [eclipse](https://github.com/camel-tooling/camel-lsp-client-eclipse) plugins
I think the best is to import the 3 projects and build them after modifications, it should launch the basic tests.
Let me know if you need help.

**Comment by djelinek** [comment]
verified with master branch
