### ISSUE TITLE
Provide completion with potential ids of direct/direct-vm/vm/seda with XML DSL

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#158]
for instance, if I have a file with:
```
<from uri="direct:anId"/>

<...>

<to uri="direct:"/>
```

completion on the "to after the ':' character should provide "anId".

**Comment by lhein** [comment]
merged PR

**Comment by tsedmik** [comment]
Hi @lhein, there is no need to assign issues me. It is sufficient to move it to _on QA_ in planning board ;-)

**Comment by tsedmik** [comment]
verified with master branch (in Eclipse IDE)
