### ISSUE TITLE
Provide support for languages used by Camel-K

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#163]
see samples in folder https://github.com/apache/camel-k/tree/master/runtime/examples

it seems that the main one will surely be groovy so maybe start with it.

**Comment by apupier** [comment]
@nicolaferraro Do you have completion for the Java API available when using Groovy files? https://github.com/apache/camel-k/blob/master/runtime/examples/camel-caffeine.groovy
If yes, how is it done? How groovy knows that _from('timer:tick').set_ can provide completion for _setBody_ ?
The other question, to leverage the LSP for Camel, how can we detect that a groovy file is a "Camel" one? so that when there is a _from('_ , we can provide completion for all Camel components? (and don't provide completion for all Camel components in case it is not a Camel file but another API used)?

**Comment by nicolaferraro** [comment]
Good questions @apupier. For the detection part, we've not defined yet any mechanism to "mark" a groovy file as "Camel-based". Suggestions are welcome.

For the auto-completion part, it's like the script lives inside the [`configure()` method of a `RouteBuilder`](https://github.com/apache/camel-k/blob/3f7ca35ee86b969ed102763ba4ec1b030a6ea8bf/runtime/groovy/src/main/groovy/org/apache/camel/k/groovy/GroovyRoutesLoader.groovy#L38), with some additional objects injected into that. So, there are at least all methods available inside the `RouteBuilder` (rest, from, restConfig, ...). @lburgazzoli may add further information. I also know that @riccardo-forina was looking into autocompletion for the experimental Camel K UI.

**Comment by lburgazzoli** [comment]
For camel-k we should assume that all the code is **always** camel code as for scripting languages such as groovy/kotlin/js, the code is evaluated as if it were the implementation of RouteBuilder's configure method.

We may think about unsing a shebang style comment or emacs file variables to help tooling. Eventually we could define a new ".kamelet" file extension and leverage shebang/emacs for language detection

**Comment by apupier** [comment]
From the Language server side, I think it won't be trivial to provide the methods available in RouteBuilder. Currently, the language server is not taking care of that as it is handled by classic java or xml editors. Not sure how to let classical kotlin/groovy/javascript tool handle it. or maybe the Language server will need to provide this support for this part too, it will require to embed several different language parsers but that's a possibility. In this case, I think that we would first concentrate on a single one such as groovy.

Having a specific extension would be nice to leverage the current Language Server. Maybe need to have a different extension for Groovy/kotlin/javascript? like "\<filename>.kameletgroovy"/"\<filename>.kameletkotlin" or maybe a "double extension" like "\<fileName>.kamelet.groovy"?
Using a shebang seems possible too, I'm wondering if it won't complicate integrations for the "classical" kotlin/groovy/javascript tools.

**Comment by apupier** [comment]
here is an example for Camel-K Groovy completion if we choose to use a specific filename like *.kamel.groovy:
https://github.com/apupier/camel-language-server-1/tree/163-basicblindCompletionForKamelGroovy
https://github.com/apupier/camel-lsp-client-vscode/tree/163-supportcamelKGroovy
https://github.com/apupier/camel-lsp-client-eclipse/tree/163-supportCamelKGroovy

![image](https://user-images.githubusercontent.com/1105127/57712121-5bcbac00-7670-11e9-9b69-3b8d6b9ce7f8.png)
![image (1)](https://user-images.githubusercontent.com/1105127/57712133-6423e700-7670-11e9-95fa-378c66aa7cc6.png)
![image (2)](https://user-images.githubusercontent.com/1105127/57712155-6f771280-7670-11e9-9a80-1549cd8dc2c7.png)

**Comment by apupier** [comment]
updated the branch to no more be based on filename *.kamel.groovy but can be either:
- filename *.camelk.groovy
- contents starts with shebang #!/usr/bin/env camel-k

**Comment by apupier** [comment]
@lburgazzoli @nicolaferraro is  #!/usr/bin/env camel-k the shebang you had in mind? if not, which one? Does it require some modifications on Camel-K runtime?

**Comment by lburgazzoli** [comment]
Yes it does requires some modification on camel-k side. 

Would it also be possible to support something like vim's modeline ? that would be simpler as settings are stored as a comment

**Comment by apupier** [comment]
> Would it also be possible to support something like vim's modeline ? that would be simpler as settings are stored as a comment

I don't get where vim's modeline applies in our context. Can you precise please?

What do you mean by setting will be stored as comments? You mean that instead of `#!/usr/bin/env camel-k` shebang, we can use something like `/* Camel-K file */`?
If yes, this can be easily be done by modifying one line of code.

**Comment by lburgazzoli** [comment]
Correct, vim modeline are vim settings embedded in a comment (with precise limitations) so it we can have for example:

     // camel-k: language=groovy

there is a vs code extension that does something similar for code itself

    https://marketplace.visualstudio.com/items?itemName=chrislajoie.vscode-modelines

**Comment by apupier** [comment]
updated branch to have it also when file is starting with "// camel-k:"
I have not found a Modeline parser written tin Java, so as a first iteration, i propose to simply force the first line to be Modeline like and start with "// camel-k:"

![image](https://user-images.githubusercontent.com/1105127/60675955-e74a0800-9e7d-11e9-90f8-c798bc702206.png)

I think we can start review and integrate it in extensions with the current state of the PRs as a first iteration.
https://github.com/camel-tooling/camel-language-server/pull/248
https://github.com/camel-tooling/camel-lsp-client-vscode/pull/110
https://github.com/camel-tooling/camel-lsp-client-eclipse/pull/85

**Comment by apupier** [comment]
current state:
- Camel URI completion and hover are supported in java/groovy/kotlin/xml/javascript and javascript
- requires first line `// camel-k : ` or filename `*.camelk.(groovy/kotlin/javascript` or xml with correct namespace or java with camel word inside

there is no support for the java/groovy/kotlin/javascript/xml provided by this server. For keeping this server relatively lightweight, we let each IDEs provides support for them. Which means with Camel-K standalone files, there is usually no support as-is for java/kotlin/groovy/javascript.

**Comment by apupier** [comment]
closing this one as we reached a "first iteration" which is providing relatively good added-value
Please open more specific issues for other issues (either on this repo or on https://issues.redhat.com/browse/FUSETOOLS2 )
