### ISSUE TITLE
Move log file to temporary folder

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#174]
it will avoid this behavior https://github.com/camel-tooling/camel-lsp-client-vscode/issues/71

**Comment by djelinek** [comment]
@apupier I am not able to found tmp folder for log file, where is it located ? Can you please provide me some easy steps to reproduce thisnew behaviour please ?

I tried that with `camel-lsp-server-1.1.0-SNAPSHOT`

**Comment by apupier** [comment]
@djelinek it is now located in java.io.tmpDir, on Windiws by default, it would be in something like C:\Users\Aurelien Pupier\AppData\Local\Temp
it is still called log-camel-lsp.out

**Comment by djelinek** [comment]
verified - camel-lsp-server-1.1.0-SNAPSHOT
