### ISSUE TITLE
Rename "diagnostics" which hides the field declared at line 68 in DiagnosticService class

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#180]
https://sonarcloud.io/project/issues?id=camel-lsp-server&issues=AWbuYp1ETJjFgJLT0T00&open=AWbuYp1ETJjFgJLT0T00

![image](https://user-images.githubusercontent.com/1105127/48257924-36858900-e414-11e8-8fc6-ab60364857b9.png)

or maybe better to rename the fields? or both?

**Comment by djelinek** [comment]
verified with master branch
