### ISSUE TITLE
Upgrade assertj to have same version in all projects to be compatible with Infinitest

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#195]
it seems that several assertj versions are not working with assertj.

Last working version is 3.10.0

**Comment by apupier** [comment]
NoSuchMethodError (org.assertj.core.api.Assertions.assertThat(Ljava/lang/String;)Lorg/assertj/core/api/AbstractStringAssert;) in 0,17.testProvideCompletionForCamelBlueprintNamespace[ahc:ht - Position 

![image](https://user-images.githubusercontent.com/1105127/49277080-b71e2f00-f480-11e8-9d99-ec033af80993.png)

**Comment by djelinek** [comment]
verified with master branch
