### ISSUE TITLE
Diagnostics on Camel URI is not working after closing editor without save

### ISSUE THREAD

**Issue by djelinek** [camel-tooling/camel-language-server#204]
### Environment

- Apache Camel Language Server release version date: **1.1.0-SNAPSHOT**
- OS:
    - [x] Linux (*RHEL*, ***Fedora***, *Ubuntu*, ...)
    - [ ] Windows
    - [ ] Mac OS
- Apache Camel Client for:
    - [x] Eclipse
    - [ ] VS Code
    - [ ] Eclipse Che
    - [ ] OpenShift.io

### Description of wrong behavior

- If there are changes, which causes inside XML editor some error and then is editor close without saving these changes, after reopening a same file there is still shown error. (see example bellow).

### Exact steps to reproduce issue

![diagnostic-err](https://user-images.githubusercontent.com/18696866/52124556-de80ac00-2629-11e9-84ba-2e76eee54a50.gif)

**Comment by apupier** [comment]
technical: it might just a question of calling the diagnostic on opening of a document in the language server

**Comment by djelinek** [comment]
verified – Tooling for Apache Camel 1.0.0.201905161153, Eclipse 2019-03
