### ISSUE TITLE
Disable XML external entity (XXE) processing.

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#208]
# Issue informations

issue newly reported by Sonar: https://sonarcloud.io/project/issues?id=camel-lsp-server&issues=AWi5L7ZXqh3OODMju8i4&open=AWi5L7ZXqh3OODMju8i4

risk is low. A user would need to open a malicious file and this file needs to be Camel one.

**Comment by tsedmik** [comment]
verified with master branch
