### ISSUE TITLE
Camel LSP reports errant issue with Camel URI having lenient component properties or using properties

### ISSUE THREAD

**Issue by bfitzpat** [camel-tooling/camel-language-server#220]
# Issue informations

> Define issue title **short** and **most specific** to the problem.
> Tag each new issue with relevant **LABELS** (*Bug*, *Improvement*, etc.).

## **BUG** report

When writing a user story for wsdl2rest, I discovered that the VS Code Camel LSP extension is reporting a "problem" in the following URI:

```
<toD id="_toWeather" uri="http://api.openweathermap.org/data/2.5/weather?${property.weatherUri}"/>
```

The problem reported is: Unknown option -- but this is a valid HTTP URL and runs fine in the Camel runtime. 

The complete route is:
```
        <route id="_weather">
            <from uri="direct:getWeather"/>
            <!-- get application ID from https://home.openweathermap.org/api_keys when you sign up for a free account -->
            <setProperty propertyName="appId">
                <constant>UPDATE</constant> <!-- replace this with your API key -->
            </setProperty>
            <setProperty propertyName="weatherUri">
                <simple>q=$simple{in.header.cityName},$simple{in.header.countryName}%26APPID=${property.appId}%26mode=xml</simple>
            </setProperty>
            <toD id="_toWeather" uri="http://api.openweathermap.org/data/2.5/weather?${property.weatherUri}"/>

            <!-- output the response -->
            <setBody id="_setWeatherBody">
                <simple>Received a weather response: ${body}</simple>
            </setBody>
            <to id="_toStream" uri="stream:out"/>
        </route>
```

### Environment

Language Support for Camel Server extension 0.0.14

- Apache Camel Language Server release version date: e.g. "**1.0.0-SNAPSHOT**, **Jun-04**" ?
- OS:
    - [ ] Linux (*RHEL*, *Fedora*, *Ubuntu*, ...)
    - [X] Windows
    - [ ] Mac OS
- Apache Camel Client for:
    - [ ] Eclipse
    - [X] VS Code
    - [ ] Eclipse Che
    - [ ] OpenShift.io

### Description of wrong behavior

- see problem description

### Exact steps to reproduce issue

1. Clone https://github.com/bfitzpat/wsdl2rest-user-story
2. Create new workspace with it
3. Open src/main/resources/camel-context.xml
4. Search for "<toD id="_toWeather" " line
5. Look in problems view

### Description

- ...

### Expected behaviour

- Should be valid 

### Screenshot (*optional*)

![image](https://user-images.githubusercontent.com/530878/55236146-e35e7800-51f4-11e9-8aea-0d03ca37ffe4.png)

**Comment by bfitzpat** [comment]
This is NOT a critical issue.

**Comment by apupier** [comment]
the error is reported by Camel itself. Camel Language Server is just wrapping the reported error. I reported it in Camel https://issues.apache.org/jira/browse/CAMEL-13382

**Comment by apupier** [comment]
hum seems that it is related to the usage of lenient "parameter" which is set to true.
Not sure when to set it to true and not to have the correct behavior

**Comment by bfitzpat** [comment]
Yeah, it was an odd case I suspect. Not critical, but wanted to make sure we knew about it.

**Comment by apupier** [comment]
the timer component which has no lenient properties is reporting a validation error too.
timer:timerName?${property.weatherUri}

so seems 2 issues:
- lenient properties
- validation which is not able to detect that a property is used for toD

**Comment by davsclaus** [comment]
The property placeholder should be `{{xxx}}` style. Why are you using `${xxx}` style?

**Comment by bfitzpat** [comment]
I will try shifting to the `{{}}` style in my local project and see what happens. Thanks @davsclaus

**Comment by bfitzpat** [comment]
> I will try shifting to the `{{}}` style in my local project and see what happens. Thanks @davsclaus

Trying with `{{property.weatherUri}}` or `{{weatherUri}}` gets me this:
```
[?[1;31mERROR?[m] Failed to execute goal ?[32morg.springframework.boot:spring-boot-maven-plugin:2.1.1.RELEASE:run?[m ?[1m(default-cli)?[m on project ?[36msimple?[m: ?[1;31mAn exception occurred while running. null?[m: InvocationTargetException: org.apache.camel.FailedToCreateRouteException: Failed to create route _weather at: >>> DynamicTo[] <<< in route: Route(_weather)[[From[direct:getWeather]] -> [SetProperty[ap... because of Property with key [weatherUri] not found in properties from text: http://api.openweathermap.org/data/2.5/weather?{{weatherUri}} -> ?[1m[Help 1]?[m
```

**Comment by davsclaus** [comment]
Yes if you run the application you need to setup those properties values in application.properties etc.

**Comment by bfitzpat** [comment]
@davsclaus Can you point me to an example where that is done? I'm just getting my feet wet in some of the intricacies of Camel development and would appreciate a nudge in the right direction.

**Comment by davsclaus** [comment]
Yes @bfitzpat just add the properties to that application.properties file. There are also some SB camel examples at: https://github.com/apache/camel/tree/master/examples#examples

**Comment by davsclaus** [comment]
The issue with `${ }` style properties is also in this FAQ: http://camel.apache.org/how-do-i-use-spring-property-placeholder-with-camel-xml.html
