### ISSUE TITLE
Wrong Apache Camel Validation returned when uri is finishing with &amp;

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#225]
# Issue informations

![image](https://user-images.githubusercontent.com/1105127/55878951-cc793780-5b9d-11e9-9c46-7e7d109549ad.png)
it is showing something in problems view in Theia only. In VS Code, there is not hing visible.

### Environment

- Apache Camel Language Server release version date: e.g. "**1.0.0-SNAPSHOT**, **Jun-04**" ?
- OS:
    - [ ] Linux (*RHEL*, *Fedora*, *Ubuntu*, ...)
    - [ ] Windows
    - [ ] Mac OS
- Apache Camel Client for:
    - [ ] Eclipse
    - [ ] VS Code
    - [ ] Eclipse Che
    - [ ] OpenShift.io
    - [x] Eclipse Theia

### Description of wrong behavior

- ...

### Exact steps to reproduce issue

docker run -it -p 3000:3000 -v "C:/Users/Aurelien Pupier/theiatmp:/home/project:cached" theiaide/theia-full:latest

use deploy plugin by id command:
vscode:extension/camel-tooling.vscode-apache-camel
vscode:extension/redhat.vscode-xml

create an xml file with content:
```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd        http://camel.apache.org/schema/spring http://camel.apache.org/schema/spring/camel-spring.xsd">
    <camelContext id="cbr-example-context" xmlns="http://camel.apache.org/schema/spring">
        <route id="cbr-route">
            <from id="_from1" uri="timer:timerName?delay=1000"/>
            <log id="_log1" message="Receiving order ${file:name}"/>
            <choice id="_choice1">
                <when id="_when1">
                    <xpath id="_xpath1">/order/customer/country = 'UK'</xpath>
                    <log id="_log2" message="Sending order ${file:name} to the UK"/>
                    <to id="_to1" uri="file:work/cbr/output/uk"/>
                </when>
                <when id="_when2">
                    <xpath id="_xpath2">/order/customer/country = 'US'</xpath>
                    <log id="_log3" message="Sending order ${file:name} to the US"/>
                    <to id="_to2" uri="file:work/cbr/output/us"/>
                </when>
                <otherwise id="_otherwise1">
                    <log id="_log4" message="Sending order ${file:name} to another country"/>
                    <to id="_to3" uri="file:work/cbr/output/others"/>
                </otherwise>
            </choice>
            <log id="_log5" message="Done processing ${file:name}"/>
        </route>
    </camelContext>
</beans>
```
change timer:timerName?delay=1000 by timer:timerName?delay=1000xx&amp;

### Description

- ...

### Expected behaviour

- ...

### Screenshot (*optional*)

- ...

**Comment by djelinek** [comment]
verified - vscode LSP client 0.0.14.latest
