### ISSUE TITLE
Use https instead of http in source code

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#233]

**Comment by tsedmik** [comment]
@apupier I see 216 uses of `http` in the current master branch. What about them? I tried `https` on some of them and it seems to be working.

**Comment by apupier** [comment]
Can you precise on which one it is working? In theory I left only the xml namespaces which cannot be replaced to have everything working correctly. But I might have miss some

**Comment by apupier** [comment]
I replaced in comments too. I think that all the ones that are left are xml namespace and so needs to be kept as-is

**Comment by tsedmik** [comment]
Verified with master branch
