### ISSUE TITLE
Provide Completion for Camel properties in an application.properties

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#239]
from @davsclaus 
"Another idea is to have code completion for configuring components via application.properties file - ala spring boot. You can find the known options in the camel-catalog for "component level"
also for c3m3 you can configure some common camel options on camel.main.xxx -- https://github.com/apache/camel/blob/master/examples/camel-example-main/src/main/resources/application.properties. But this requires camel-k migrated to use main from c3m3 in their upcoming releases which @Luca Burgazzoli et all will work on
you can use camel-case style in application.properties."

- the example is in apache/camel repository but if I understood well the feedback was coming from Camel-K usage. Would it be something camel-generic or specific to Camel-K?
- "But this requires camel-k migrated" I have not found a related issue in camel-k repository. @lburgazzoli . Do you have one already created? Can you point it here please?

**Comment by lburgazzoli** [comment]
It has been migrated but the application.properties is "hidden" for the user POW as it has to be provided through a configmap/secret or with configuration options inside the crd.

**Comment by davsclaus** [comment]
<img width="1164" alt="Screenshot 2019-06-20 at 08 37 23" src="https://user-images.githubusercontent.com/477100/59826502-bc689b80-9336-11e9-91e2-544936fadcf2.png">

**Comment by davsclaus** [comment]
So for Camel 3 M4 we have just added support for running Camel standalone (Camel Main) where you can have code assistance in the application.properties by "simulating" as if it was spring boot, so the tool uses SB code completions. 

There is an example showing this in examples/camel-example-main-artemis.

You need to run a maven plugin once to setup this. But what the maven plugin does would be possible to bake into our tooling.

**Comment by apupier** [comment]
> You need to run a maven plugin once to setup this. But what the maven plugin does would be possible to bake into our tooling.

do you mean that a good thing would be to have the completion even without calling the maven plugin which is setting up SpringBoot properties? Or more to have an action from the tooling to trigger the same setup (using maven plugin or directly the code behind the maven plugin) then to rely on the SpringBoot tooling?

To be sure, it is this plugin which is responsible to do the work, right? https://github.com/apache/camel/tree/master/tooling/maven/camel-main-package-maven-plugin

**Comment by davsclaus** [comment]
Yes its that plugin. 

If the Camel tooling has natural support for application.properties then it doesn't really matter how it does that. What we did with that maven plugin above was to use spring boot tooling for this by fooling it to think its a spring boot project (we generate spring boot metadata json files). That works as a "clever hack" until the Camel tooling has it out of the box.

The Camel tooling have the information from the camel-catalog for all the components etc. For the "main configuration of Camel" then the details are not (yet) in camel-catalog but only in camel-main JAR as this file: 

https://github.com/apache/camel/blob/master/core/camel-main/src/main/resources/META-INF/camel-main-configuration-metadata.json

**Comment by apupier** [comment]
created https://issues.apache.org/jira/browse/CAMEL-14309 to have the information in the catalog
created https://issues.apache.org/jira/browse/CAMEL-14310 to ease usage of it

**Comment by apupier** [comment]
this has been implemented
