### ISSUE TITLE
Provide completion/validation/hover for camel.source.url and camel.sink.url values on Camel Kafka connect property file

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#254]

**Comment by apupier** [comment]
@valdar @oscerd 
Please validate that I understood correctly.

a good help for Camel Kafka Connect users would be to have completion/validation/hover on camel.source.url and camel.sink.url on properties file such as https://github.com/jboss-fuse/camel-kafka-connector/blob/master/examples/CamelAWSS3SourceConnector.properties ?

If yes, is it possible to reuse the normal Camel Catalog? If not, at least as a first iteration would it be convenient even if providing some unsupported components?
camel.source.url are corresponding to a "from" and camel.sink.url to a "to"?

**Comment by apupier** [comment]
provided a PR https://github.com/camel-tooling/camel-language-server/pull/257 following my previous assumptions

@valdar or @oscerd if you can confirm that it makes sense

![image](https://user-images.githubusercontent.com/1105127/62111903-e310df00-b2b1-11e9-8f7c-3187503185a9.png)

**Comment by oscerd** [comment]
That's great!

**Comment by djelinek** [comment]
verified with VS Code 1.37.0 and Language Support for Apache Camel 0.0.16
