### ISSUE TITLE
Provide support for Camel-K Kotlin files

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#255]
https://trello.com/c/tSJjhJJf/37-completion-for-camel-uri-for-camel-k-kotlin-files
https://github.com/camel-tooling/camel-language-server/issues/163

example file https://github.com/apache/camel-k/blob/master/examples/kotlin-routes.kts

detect Kotlin files when one of them:
- filename *.camelk..kts
- modeline -like starting with` // camel-k: language=kotlin`

**Comment by apupier** [comment]
![Webp net-gifmaker](https://user-images.githubusercontent.com/1105127/62052780-81e7fd80-b216-11e9-9837-929af365576d.gif)

**Comment by apupier** [comment]
![image](https://user-images.githubusercontent.com/1105127/62053161-544f8400-b217-11e9-8ed1-ec883883c79a.png)

**Comment by djelinek** [comment]
verified with VS Code 1.37.0 and Language Support for Apache Camel 0.0.16
