### ISSUE TITLE
Support websocket connection

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#260]
Currently the connection is on stdin/stdout.
it would be useful to have websocket connection available so can be consumed from https://github.com/wylieconlon/lsp-editor-adapter

**Comment by apupier** [comment]
Websocket connection in lsp4J is coming in 0.8 version, planned to be released in August https://github.com/eclipse/lsp4j/issues/203

**Comment by apupier** [comment]
possible start o fimplementation https://github.com/apupier/camel-language-server-1/tree/260-provideWebsocketConnection but not sure what is the simplest way to use the javax.websocket.server.ServerEndpointConfig

**Comment by apupier** [comment]
as we ar enot using a classical SpringBoot project but just repackaging using springboot. I'm wondering if it is not easier/lighter to use the reference implementation Tyrus: https://tyrus-project.github.io/documentation/1.12/index/getting-started.html

**Comment by apupier** [comment]
follow-up https://github.com/camel-tooling/camel-language-server/issues/303 to allow configurable connection

**Comment by apupier** [comment]
to test it manually, recommend to use the CodeMirror example https://github.com/camel-tooling/camel-lsp-client-codemirror

**Comment by djelinek** [comment]
verified with GitHub codemirror example and locally started LSP server with --websocket parameter
