### ISSUE TITLE
Provide support for Camel-K JS Files

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#261]
https://trello.com/c/2GmkyVsb/38-completion-for-camel-uri-for-camel-k-js-files
#163

example file https://github.com/apache/camel-k/blob/master/examples/simple.js

detect JS files when one of them:

- filename *.camelk.js
- modeline-like starting with // camel-k: language=js

**Comment by djelinek** [comment]
verified with VS Code 1.37.0 and Language Support for Apache Camel 0.0.16
