### ISSUE TITLE
Provide support for Yaml files

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#284]
2 use cases (might be splitted in 2 different PRs):

- Camel-K standalone file https://github.com/apache/camel-k-runtime/blob/master/examples/camel-k-runtime-example-yaml/src/main/resources/routes.yaml
- under the hood CRD https://docs.google.com/presentation/d/1jXMuHtRvcgzUORiYTkQUslCyhBU_YuYR9LJSLWDsooo/edit#slide=id.g585e82468f_0_0
- KNative CRD (pretty sure I have seen a specific Knative CRD somewhere but cannot find references)

heuristic to provide the completion to be determined, some proposals:
- for standalone file : filename *.camelk.yaml/modeline like and a from/to inside steps and followed by an uri? (format is not yet fully determined as far as I know maybe we can support the different ones) https://docs.google.com/presentation/d/1jXMuHtRvcgzUORiYTkQUslCyhBU_YuYR9LJSLWDsooo/edit#slide=id.g5fe2be6cc0_2_64
- maybe api version which is on the first line and then the from/to from inside a sources/sinks?

Will require to add the filetype association in each client IDE

**Comment by lhein** [comment]
feature has been implemented @djelinek @tsedmik

**Comment by apupier** [comment]
found reference to the Knative CRD https://github.com/knative/eventing-contrib/blob/master/camel/source/samples/
it seems to work with it too. Maybe will worth to have test for this case too

**Comment by apupier** [comment]
seems that the initial iteration is working fine.
closing this issue. We can open more specific issue.
