### ISSUE TITLE
Provide configurable websocket connection

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#303]
currently running on localhost:8025/camel-language-server

it might be useful to be able to configure each part

**Comment by apupier** [comment]
websocket connection are configurable with:
`--port=`
`--hostname=`
`--contextPath=`

which is then exposing something like:
`ws://<hostname>:<port><contextPath>/camel-language-server`

**Comment by djelinek** [comment]
verified with GitHub codemirror example and locally started LSP server with --websocket parameter
