### ISSUE TITLE
Master build is failing [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar (default-cli) on project camel-lsp-server: Unable to read /home/travis/build/camel-tooling/camel-language-server/target/jacoco.exec to determine JaCoCo binary format.: EOFException

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#310]
```
[WARNING] Property 'sonar.jacoco.reportPath' is deprecated (JaCoCo binary format). 'sonar.coverage.jacoco.xmlReportPaths' should be used instead (JaCoCo XML format). Please check that the JaCoCo plugin is installed on your SonarQube Instance.
[WARNING] Property 'sonar.jacoco.reportPaths' is deprecated (JaCoCo binary format). 'sonar.coverage.jacoco.xmlReportPaths' should be used instead (JaCoCo XML format). Please check that the JaCoCo plugin is installed on your SonarQube Instance.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  28.759 s
[INFO] Finished at: 2019-09-30T13:28:10Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar (default-cli) on project camel-lsp-server: Unable to read /home/travis/build/camel-tooling/camel-language-server/target/jacoco.exec to determine JaCoCo binary format.: EOFException -> [Help 1]
```

might be due to environment change as the code change seems completely unrelated

**Comment by apupier** [comment]
seems a bug with Sonar/jacoco https://support.cloudbees.com/hc/en-us/articles/205074234-SonarQube-reporting-is-failing-with-a-jacoco-error-Incompatible-version-1007

**Comment by apupier** [comment]
doing in 2 mvn builds, the test and teh sonar analysis is no more working... don't know why. the simple workaround is to launch both in same command.
Will need to report the same modifications on all Maven Java projects (maybe others too?)

**Comment by apupier** [comment]
so doing in same builds was working locally but not on CI... I'm suspecting that it was caused by previous build states...
trying to follow https://community.sonarsource.com/t/coverage-test-data-importing-jacoco-coverage-report-in-xml-format/12151 but seems the case of unit and integration test is not covered (in doc)

**Comment by apupier** [comment]
build no more failing at the cost of not having code coverage anymore. Created https://github.com/camel-tooling/camel-language-server/issues/313 to restore it

**Comment by djelinek** [comment]
verified with master branch
