### ISSUE TITLE
Refactor getCorrespondingParserFileHelper to reduce cognitive complexity

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#316]
https://sonarcloud.io/project/issues?id=camel-lsp-server&issues=AWxRVsbydg2jiL0y_QTx&open=AWxRVsbydg2jiL0y_QTx

![Screenshot from 2019-10-04 15-53-45](https://user-images.githubusercontent.com/1105127/66213003-32fb9000-e6bf-11e9-8956-a6a51432de01.png)

**Comment by apupier** [comment]
maybe a visitor pattern? deporting computing in each parser class? (and will surely need some helper class oto share some common methods)
need to take care on order/override for the ones that have very similar conditions

**Comment by kapilgahlot1998** [comment]
@apupier I can see this issue is still present. 
Can I take this issue.?? 
I have experienced of solving cognitive complexity.

**Comment by apupier** [comment]
Thanks for proposing your help. I assigned the issue to you so that you can work on it limiting the risk that someone else is doing it too.
