### ISSUE TITLE
Using variables in route throws an error

### ISSUE THREAD

**Issue by JakesIV** [camel-tooling/camel-language-server#317]
# Issue informations

> When using variables like from("{{fromRoute}}") throws a blank error like below in eclipse
Description	Resource	Path	Location	Type
	RestCamelRoute.java	/rest-learncamel-spring-boot/src/main/java/com/learncamel/routes	line 48	org.eclipse.lsp4e.diagnostic

### Environment

- Apache Camel Language Server release version date:   Tooling for Apache Camel based on Apache Camel implementation of Language Server Protocol	1.0.0.201909171309	com.github.cameltooling.lsp.eclipse.client.feature.feature.group	null

- OS:
    - [ ] Windows
- Apache Camel Client for:
    - [ ] Eclipse

### Description of wrong behavior

The tooling should not report from("{{fromRoute}}") as an error as the operation is coming with the variable. The only way to fix this is to add the operation like this
from("https://{{fromRoute}}")
### Exact steps to reproduce issue

1. add route to routebuilder class using full parameter like from("{{fromRoute}}") or to({{toRoute}})
2. add variable to application.properties for fromRoute: https://serviceendpoint/service1
3. the application will compile but the editor will throw a blank error

### Expected behaviour

- The expected behavior is for the editor to recognise that a variable is used but inpecting the opening brackets  {{somevarible}} and then ignore this scenario as it obviously cannot be validated but the plugin.

### Screenshot (*optional*)

- 
![image](https://user-images.githubusercontent.com/27683866/66453079-65144580-ea63-11e9-8536-4a60871d6177.png)

**Comment by djelinek** [comment]
verified - eclipse-2019-03 (4.11.0), Tooling for Apache Camel LSP 1.0.0.201910110708
