### ISSUE TITLE
Support additional catalogs

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#45]
some catalogs are provided outside of Camel core, it will be a good idea to have a way to include them in the completion/validation/doc. it will help to focus on a specific vertical for instance.

**Comment by davsclaus** [comment]
The Camel IDEA plugin supports 3rd party Camel components that has the metadata JSon files in their own JAR file. The camel-catalog is jut a single JAR with all the stuff that are in a Camel release OOTB. But each of those Camel JARs also have that metadata JSon in their own JAR file.

So from tooling point of view, if you are able to look inside the JARs you should be able to find those JSon schema files.

Oh and this requires that those custom Camel components are built with the metadata JARs included, like for example the camel-archetype-component shows:
https://github.com/apache/camel/blob/master/archetypes/camel-archetype-component/src/main/resources/archetype-resources/pom.xml#L109

**Comment by apupier** [comment]
> So from tooling point of view, if you are able to look inside the JARs you should be able to find those JSon schema files.

currently we have no access to classpath and dependencies.
it is possible to ask some extra parameters for configuring the server.
i think that as a first step we should use a simple String parameter with the json file as it will require less work to implement (but more for users I know)
A second step might be to provide a path to the jar, in this case, either server is launched on the same machine (which is the case anyway for now and surely for a long time).
We can have both parameters available for configuration.

**Comment by ctron** [comment]
I think you could do the following:

* Create a maven plugin which will extract the JSON information from a local project and write it to a combined JSON in `target/`. Set M2Eclipse properties in the maven plugin so that it will be included automatically by M2Eclipse.
* Enhance the Camel LS to pick up that file

This way you would have access to the exact classpath/dependencies information of the project but still use the LSP approach.

**Comment by apupier** [comment]
> I think you could do the following:
> 
> Create a maven plugin which will extract the JSON information from a local project and write it to a combined JSON in target/. Set M2Eclipse properties in the maven plugin so that it will be included automatically by M2Eclipse.
> Enhance the Camel LS to pick up that file
> This way you would have access to the exact classpath/dependencies information of the project but still use the LSP approach.

thanks for the idea.
It will enhance the experience for Eclipse Desktop IDE. This might be a possibility as a third iteration.
It still requires the first iteration of having the LS consuming a file as a parameter.

**Comment by ctron** [comment]
> It still requires the first iteration of having the LS consuming a file as a parameter.

IIRC a LS can actually traverse through the file system, not sure if this still is the case … but in this case you could simply walk upwards the file system tree until you find a folder `target` which contains a file `foobar` and then use this. But yes, the ability to specify a file would be more deterministic.

**Comment by apupier** [comment]
additional components can now be added https://issues.redhat.com/browse/FUSETOOLS2-72
see https://github.com/camel-tooling/camel-language-server#additional-camel-components

there is room for improvements (for instance using Maven GAV https://issues.redhat.com/browse/FUSETOOLS2-183 ).
Closing this generic one. Will handle with separated JIRA issue other improvements.
