### ISSUE TITLE
add deployment to maven central

### ISSUE THREAD

**Issue by lhein** [camel-tooling/camel-language-server#5]
extend the travis script to push snapshots and releases to some official and public maven repository

**Comment by lhein** [comment]
already added basic configuration via #10 

need to generate keys and stuff still to make it work

**Comment by apupier** [comment]
request for rights on Sonatype repo: https://issues.sonatype.org/browse/OSSRH-38608

**Comment by apupier** [comment]
tutorial followed to do it: http://www.debonair.io/post/maven-cd

**Comment by lhein** [comment]
no success - manual deployment works though

**Comment by apupier** [comment]
current error on CI:

> bad decrypt
> 140623337141920:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:evp_enc.c:539:
> gpg: no valid OpenPGP data found.
> gpg: Total number processed: 0
> first 2 lines are the failing decrypt of the key file
> last 2 lines are the failing import of the keys

**Comment by apupier** [comment]
on the CI, the openSSL version is openssl version
OpenSSL 1.0.1f 6 Jan 2014
https://travis-ci.org/camel-tooling/camel-language-server/jobs/365012271#L85

the current key has been encrypted with 1.1.0.h-1 version

**Comment by apupier** [comment]
some official travis doc to encrypt files: https://docs.travis-ci.com/user/encrypting-files/

**Comment by apupier** [comment]
a travis ci maven deploy skeleton: https://github.com/making/travis-ci-maven-deploy-skelton
it seems to be linked to a specific Sonatype account
