### ISSUE TITLE
On Completion, insert and replace when there is something after the cursor

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-language-server#55]
for instance, there is "timer", I put the cursor after the t and choose twitter

current result is:
"twitter:kindimer"

expected result would be:
"twitter:kind"

same applies for options.

How to handle the remaining parts if more complex such as:
"timer:value?delay=1000"
if I autocomplete after the t with twitter:kind, what would be the result?
"twitter:kind"
"twitter:kind?delay=1000"
"twitter:value"

**Comment by lhein** [comment]
This is a client side behaviour from what I found out. In Eclipse it is controlled by Settings for Java but for XML there seems to be no setting at all. For VSCode I haven't checked yet.

**Comment by apupier** [comment]
this can be done on server side with the textEdit parameter https://microsoft.github.io/language-server-protocol/specification
![image](https://user-images.githubusercontent.com/1105127/44076861-025a6efe-9fa2-11e8-93dc-a90e1f9c2050.png)

**Comment by tsedmik** [comment]
verified with master branch
